// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type OTPType string

const (
	OTPTypeUserOtp     OTPType = "UserOtp"
	OTPTypeEverntOtp   OTPType = "EverntOtp"
	OTPTypeRegisterOtp OTPType = "RegisterOtp"
)

func (e *OTPType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OTPType(s)
	case string:
		*e = OTPType(s)
	default:
		return fmt.Errorf("unsupported scan type for OTPType: %T", src)
	}
	return nil
}

type NullOTPType struct {
	OTPType OTPType `json:"OTP_Type"`
	Valid   bool    `json:"valid"` // Valid is true if OTPType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOTPType) Scan(value interface{}) error {
	if value == nil {
		ns.OTPType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OTPType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOTPType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OTPType), nil
}

type Attendance struct {
	ID        string           `json:"id"`
	User      string           `json:"user"`
	EventId   string           `json:"eventId"`
	Timestamp pgtype.Timestamp `json:"timestamp"`
	Fields    []byte           `json:"fields"`
	Verified  bool             `json:"verified"`
}

type CustomField struct {
	ID        string `json:"id"`
	EventId   string `json:"eventId"`
	FieldName string `json:"fieldName"`
	FieldType string `json:"fieldType"`
}

type Event struct {
	ID             string           `json:"id"`
	Name           string           `json:"name"`
	Description    string           `json:"description"`
	Tickets        pgtype.Int4      `json:"tickets"`
	Price          int32            `json:"price"`
	Organization   string           `json:"organization"`
	OrgImgURL      string           `json:"orgImgURL"`
	DateTime       pgtype.Timestamp `json:"dateTime"`
	Location       string           `json:"location"`
	CreatedById    string           `json:"createdById"`
	AdditionalData pgtype.Text      `json:"additionalData"`
	CreatedAt      pgtype.Timestamp `json:"createdAt"`
	UpdatedAt      pgtype.Timestamp `json:"updatedAt"`
}

type EventOwnership struct {
	A string `json:"A"`
	B string `json:"B"`
}

type Otp struct {
	ID        string           `json:"id"`
	User      string           `json:"user"`
	Otp       string           `json:"otp"`
	Data      []byte           `json:"data"`
	Type      OTPType          `json:"type"`
	ExpiresAt pgtype.Timestamp `json:"expiresAt"`
}

type Review struct {
	ID           string         `json:"id"`
	EventId      string         `json:"eventId"`
	Participants int32          `json:"participants"`
	Review       pgtype.Numeric `json:"Review"`
}

type User struct {
	ID        string           `json:"id"`
	Email     string           `json:"email"`
	Password  string           `json:"password"`
	Name      pgtype.Text      `json:"name"`
	ImgURL    pgtype.Text      `json:"imgURL"`
	CreatedAt pgtype.Timestamp `json:"createdAt"`
	UpdatedAt pgtype.Timestamp `json:"updatedAt"`
}

type UserEvent struct {
	A string `json:"A"`
	B string `json:"B"`
}
